#!/usr/bin/env bash

# yay
sudo pacman -S --needed --noconfirm git base-devel
git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg -si --noconfirm

hash -r

yay -Sy --needed --noconfirm brave-bin
