#!/usr/bin/env bash

curl -LO https://dot.net/v1/dotnet-install.sh

chmod +x ./dotnet-install.sh

sudo ./dotnet-install.sh --install-dir /usr/share/dotnet -channel STS -version latest
sudo ./dotnet-install.sh --install-dir /usr/share/dotnet -channel STS -version 8.0.409

# do I need it?
# dotnet tool install -g csharpier

dotnet tool install --global dotnet-ef

rm ./dotnet-install.sh

sudo ln -s /usr/share/dotnet/dotnet /usr/local/bin/dotnet

echo "fs.inotify.max_user_instances=8192" | sudo tee /etc/sysctl.d/99-max-inotify.conf
echo "fs.inotify.max_user_watches=1048576" | sudo tee /etc/sysctl.d/99-max-inotify.conf
