#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed pipewire pipewire-pulse playerctl pavucontrol telegram-desktop

systemctl --user enable pipewire pipewire-pulse
systemctl --user start pipewire pipewire-pulse
