#!/usr/bin/env bash

sudo pacman -S --needed --noconfirm nodejs npm

# work
# sudo npm config set strict-ssl false

# do i need it?
# sudo npm install -g typescript-language-server typescript vscode-langservers-extracted js-beautify
