#!/usr/bin/env bash

sudo pacman -S --needed --noconfirm libx11 libxft libxinemara

# check if error has gone
hash -r

cd $HOME/personal/

git clone https://github.com/stasnocap/dwm
cd dwm
sudo make clean install
cd ..

git clone git://git.suckless.org/dmenu
cd dmenu
sudo make clean install
cd ..

git clone https://github.com/stasnocap/st
cd st
sudo make clean install

cd $HOME/personal/dev
