#!/usr/bin/env bash

sudo pacman -S --needed --noconfirm libx11 libxft libxinemara

cd $HOME

git clone https://github.com/stasnocap/dwm
cd dwm
sudo make clean install
cd ..

git clone git://git.suckless.org/dmenu
cd dmenu
sudo make clean install
cd ..

git clone https://github.com/stasnocap/st
cd st
sudo make clean install

cd $HOME/dev
