#!/usr/bin/env bash

sudo pacman -S --needed --noconfirm git zsh 

# work
# git config --global http.sslVerify false

hash -r

chsh -s $(which zsh)

yes | RUNZSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
